// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeU8kjo3Jbye8yO9aUaRt_ATbmbWB2aAE',
    appId: '1:1090205141971:web:308764d2ad339335c3fd26',
    messagingSenderId: '1090205141971',
    projectId: 'econnect-brew',
    authDomain: 'econnect-brew.firebaseapp.com',
    storageBucket: 'econnect-brew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdLPZTyrgENBR4plcPHpoLLi81MIhWq4',
    appId: '1:1090205141971:android:ab7733bb61fa5bbac3fd26',
    messagingSenderId: '1090205141971',
    projectId: 'econnect-brew',
    storageBucket: 'econnect-brew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjkaj56G3pIqJOBoXisZqTP1CTpRC4LM',
    appId: '1:1090205141971:ios:1dbc40674366825ac3fd26',
    messagingSenderId: '1090205141971',
    projectId: 'econnect-brew',
    storageBucket: 'econnect-brew.appspot.com',
    iosClientId: '1090205141971-c8rscju9a4m5qsehhog0b66snr6nrfld.apps.googleusercontent.com',
    iosBundleId: 'com.example.econnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjkaj56G3pIqJOBoXisZqTP1CTpRC4LM',
    appId: '1:1090205141971:ios:1dbc40674366825ac3fd26',
    messagingSenderId: '1090205141971',
    projectId: 'econnect-brew',
    storageBucket: 'econnect-brew.appspot.com',
    iosClientId: '1090205141971-c8rscju9a4m5qsehhog0b66snr6nrfld.apps.googleusercontent.com',
    iosBundleId: 'com.example.econnect',
  );
}
